heat_template_version: 2015-04-30

description: >
  Software Config to drive os-net-config with 2 bonded nics on a bridge
  With VLANS configured per network.

parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  InternalApiIpSubnet:
    default: ''
    description: IP address/subnet on the internal API network
    type: string
  StorageIpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  StorageMgmtIpSubnet:
    default: ''
    description: IP address/subnet on the storage mgmt network
    type: string
  TenantIpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  ManagementIpSubnet: # Only populated when including environments/network-management.yaml
    default: ''
    description: IP address/subnet on the management network
    type: string
  ControlPlaneSubnetCidr: # Override this via parameter_defaults
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  ControlPlaneDefaultRoute: # Override this via parameter_defaults
    description: The default route of the control plane network.
    type: string
  DnsServers: # Override this via parameter_defaults
    default: []
    description: A list of DNS servers (2 max for some implementations) that will be added to resolv.conf.
    type: comma_delimited_list
  EC2MetadataIp: # Override this via parameter_defaults
    description: The IP address of the EC2 metadata server.
    type: string
  InternalApiNetworkVlanID:
    default: ''
    description: Internal API Network Vlan ID
    type: string
  StorageNetworkVlanID:
    default: ''
    description: Storage Network Vlan ID
    type: string
  StorageMgmtNetworkVlanID:
    default: ''
    description: Storage Management Network Vlan ID
    type: string
  ManagementNetworkVlanID:
    default: ''
    description: Vlan ID for the management network traffic.
    type: string

resources:
  OsNetConfigImpl:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        os_net_config:
          network_config:
            -
              type: interface
              name: nic1
              use_dhcp: false
              dns_servers: {get_param: DnsServers}
              addresses:
                -
                  ip_netmask:
                    list_join:
                      - '/'
                      - - {get_param: ControlPlaneIp}
                        - {get_param: ControlPlaneSubnetCidr}
              routes:
                -
                  ip_netmask: 169.254.169.254/32
                  next_hop: {get_param: EC2MetadataIp}
                -
                  default: true
                  next_hop: {get_param: ControlPlaneDefaultRoute}
            -
              type: linux_bond
              name: bond0
              use_dhcp: false
              bonding_options: "mode=0"
              defroute: false
              mtu: 1580
              addresses:
               -
                 ip_netmask: {get_param: TenantIpSubnet}
              members:
                   -
                     type: interface
                     name: nic2
                     mtu: 1580
                     use_dhcp: false
                     defroute: false
                   -
                     type: interface
                     name: nic3
                     mtu: 1580
                     use_dhcp: false
                     defroute: false

            - type: linux_bridge
              name: br-intapi
              mtu: 1500
              addresses:
                - ip_netmask: {get_param: InternalApiIpSubnet}
              members:
              - type: vlan
                mtu: 1500
                device: bond0
                vlan_id: {get_param: InternalApiNetworkVlanID}

            - type: linux_bridge
              name: br-storage
              mtu: 1500
              addresses:
                - ip_netmask: {get_param: StorageIpSubnet}
              members:
              - type: vlan
                mtu: 1500
                device: bond0
                vlan_id: {get_param: StorageNetworkVlanID}


outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value: {get_resource: OsNetConfigImpl}
